/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Order;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felixmayo
 */
public class BoxUI2 extends javax.swing.JFrame {

    OrderManager orderManager;

    /**
     *Creates a new Order manager that oversees the logic of manipulating boxes.
     * Sets up the display and adds required information.
     */
    public BoxUI2() {
        initComponents();
        orderManager = new OrderManager();
        updateValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jbtn_completeOrder = new javax.swing.JButton();
        jbtn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        noBoxes = new javax.swing.JLabel();
        totCost = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_help = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_boxOrders = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_boxLength = new javax.swing.JTextField();
        txt_boxHeight = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        cmb_cardboardGrade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txt_boxWidth = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbtn_no1 = new javax.swing.JRadioButton();
        rbtn_2 = new javax.swing.JRadioButton();
        rbtn_yes3 = new javax.swing.JRadioButton();
        rbtn_yes1 = new javax.swing.JRadioButton();
        rbtn_0 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbtn_yes2 = new javax.swing.JRadioButton();
        rbtn_no3 = new javax.swing.JRadioButton();
        rbtn_1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtn_no2 = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Box Order Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jbtn_completeOrder.setText("Complete Order");
        jbtn_completeOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_completeOrderMouseClicked(evt);
            }
        });
        jbtn_completeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_completeOrderActionPerformed(evt);
            }
        });

        jbtn_add.setText("Add");
        jbtn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_addActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        noBoxes.setText("Quantity");

        totCost.setText("Cost");

        jLabel13.setText("Extras");

        btn_help.setText("Help");
        btn_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_helpActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        tbl_boxOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Size (m²)", "Grade", "Sealable", "Colours", "ReBottom", "ReCorners", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_boxOrders);
        if (tbl_boxOrders.getColumnModel().getColumnCount() > 0) {
            tbl_boxOrders.getColumnModel().getColumn(0).setResizable(false);
            tbl_boxOrders.getColumnModel().getColumn(1).setResizable(false);
            tbl_boxOrders.getColumnModel().getColumn(2).setResizable(false);
            tbl_boxOrders.getColumnModel().getColumn(3).setResizable(false);
            tbl_boxOrders.getColumnModel().getColumn(4).setResizable(false);
            tbl_boxOrders.getColumnModel().getColumn(5).setResizable(false);
            tbl_boxOrders.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel11.setText("Box Height /m:");

        txt_boxLength.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_boxLengthFocusGained(evt);
            }
        });
        txt_boxLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_boxLengthActionPerformed(evt);
            }
        });

        txt_boxHeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_boxHeightFocusGained(evt);
            }
        });
        txt_boxHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_boxHeightActionPerformed(evt);
            }
        });

        txt_quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_quantityFocusGained(evt);
            }
        });

        cmb_cardboardGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel1.setText("Box Order Form");

        txt_boxWidth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_boxWidthFocusGained(evt);
            }
        });
        txt_boxWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_boxWidthActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantity:");

        jLabel10.setText("Box Length /m:");

        jLabel2.setText("Box Width /m:");

        jLabel3.setText("Cardboard grade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(167, 167, 167))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_boxWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_boxLength, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_boxHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(cmb_cardboardGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_boxWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_boxLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_boxHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_cardboardGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        buttonGroup2.add(rbtn_no1);
        rbtn_no1.setSelected(true);
        rbtn_no1.setText("No");
        rbtn_no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_no1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_2);
        rbtn_2.setText("2");

        buttonGroup4.add(rbtn_yes3);
        rbtn_yes3.setText("Yes");
        rbtn_yes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_yes3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtn_yes1);
        rbtn_yes1.setText("Yes");
        rbtn_yes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_yes1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_0);
        rbtn_0.setSelected(true);
        rbtn_0.setText("0");
        rbtn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_0ActionPerformed(evt);
            }
        });

        jLabel5.setText("Reinforced Bottom:");

        buttonGroup3.add(rbtn_yes2);
        rbtn_yes2.setText("Yes");

        buttonGroup4.add(rbtn_no3);
        rbtn_no3.setSelected(true);
        rbtn_no3.setText("No");

        buttonGroup1.add(rbtn_1);
        rbtn_1.setText("1");
        rbtn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Sealable Top:");

        jLabel6.setText("Reinforced Corners:");

        jLabel4.setText("Colour print:");

        buttonGroup3.add(rbtn_no2);
        rbtn_no2.setSelected(true);
        rbtn_no2.setText("No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(rbtn_0)
                            .addGap(0, 0, 0)
                            .addComponent(rbtn_1)
                            .addGap(0, 0, 0)
                            .addComponent(rbtn_2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel6)
                            .addGap(32, 32, 32)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(rbtn_yes1)
                                    .addGap(0, 0, 0)
                                    .addComponent(rbtn_no1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(rbtn_yes2)
                                    .addGap(0, 0, 0)
                                    .addComponent(rbtn_no2)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtn_yes3)
                                .addGap(0, 0, 0)
                                .addComponent(rbtn_no3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(124, 124, 124))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel12)
                        .addGap(124, 124, 124)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtn_0)
                        .addComponent(jLabel4))
                    .addComponent(rbtn_1)
                    .addComponent(rbtn_2))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtn_yes1)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbtn_no1))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtn_yes2)
                        .addComponent(jLabel6))
                    .addComponent(rbtn_no2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn_yes3)
                    .addComponent(rbtn_no3)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noBoxes)
                                .addGap(181, 181, 181)
                                .addComponent(totCost))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_help))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(btn_clear)
                                        .addGap(26, 26, 26)
                                        .addComponent(btn_delete)
                                        .addGap(28, 28, 28)
                                        .addComponent(jbtn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtn_completeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(btn_help))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear)
                            .addComponent(jbtn_add)
                            .addComponent(btn_delete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totCost)
                    .addComponent(jbtn_completeOrder)
                    .addComponent(noBoxes))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_0ActionPerformed

    private void rbtn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_1ActionPerformed

    private void rbtn_yes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_yes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_yes1ActionPerformed

    private void rbtn_no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_no1ActionPerformed

    private void jbtn_completeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_completeOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_completeOrderActionPerformed

    /**
     * Checks for valid inputs when add button is selected. 
     * When the inputs pass the validation tests, the data is sent to the 
     * Order manager to add to the other boxes. 
     *
     */
    private void jbtn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_addActionPerformed
        // TODO add your handling code here:
        boolean validCheck = true;
        int outputCode;
        float boxHeight;
        float boxWidth;
        float boxLength;
        int cardboardGrade;
        int quantity;
        boolean sealableTop = rbtn_yes3.isSelected();
        int colourPrint = 3;
        boolean reBottom = rbtn_yes1.isSelected(); //considered always false
        boolean reCorners = rbtn_yes2.isSelected(); //considered always false



        //colour print
        if (rbtn_0.isSelected() == true) {
            colourPrint = 0;
        } else if (rbtn_1.isSelected() == true) {
            colourPrint = 1;
        } else if (rbtn_2.isSelected() == true) {
            colourPrint = 2;
        }

        outputCode = -2; // Input Error
        if (orderManager.checkInputFloat(txt_boxWidth.getText()) == false) {
            txt_boxWidth.setBackground(Color.red);
            validCheck = false;
        }
        if (orderManager.checkInputFloat(txt_boxHeight.getText()) == false) {
            txt_boxHeight.setBackground(Color.red);
            validCheck = false;
        }
        if (orderManager.checkInputFloat(txt_boxLength.getText()) == false) {
            txt_boxLength.setBackground(Color.red);
            validCheck = false;
        }
        if (orderManager.checkInputInt(txt_quantity.getText()) == false) {
            txt_quantity.setBackground(Color.red);
            validCheck = false;
        }
        
        if (validCheck == true) {
        boxHeight = orderManager.testFloat(txt_boxHeight.getText());
        boxWidth = orderManager.testFloat(txt_boxWidth.getText());
        boxLength = orderManager.testFloat(txt_boxLength.getText());
//        cardboardGrade = orderManager.testInt(txt_cardboardGrade.getText());
        cardboardGrade = cmb_cardboardGrade.getSelectedIndex() + 1;
        quantity = orderManager.testInt(txt_quantity.getText());
            
            
            outputCode = orderManager.addBox(boxWidth, boxLength, boxHeight,
                    cardboardGrade, colourPrint, reBottom, reCorners,
                    sealableTop, quantity);
            //@TODO adds to table
            //adds the content (that was just checked and sent to the addBox method) to the content table in the ui

            if (outputCode > 0) {
                Box box = orderManager.getLatestBox();
                DefaultTableModel model = (DefaultTableModel) tbl_boxOrders.getModel();
                model.addRow(new Object[]{box.getSize(), box.getGrade(), box.getSealableTop(), box.getColourPrint(), box.getReBottom(), box.getReCorners(), box.getQuantity()});
                clearValues();
            }

//        checks if the box has been created
        }

        updateValues();

        outputPrompt(outputCode);

    }//GEN-LAST:event_jbtn_addActionPerformed

    private void txt_boxHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_boxHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_boxHeightActionPerformed
    /**
     *Clears inputted values when the Clear button is clicked 
     */
    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearValues();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_boxWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_boxWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_boxWidthActionPerformed

    private void txt_boxLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_boxLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_boxLengthActionPerformed

    private void rbtn_yes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_yes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_yes3ActionPerformed

    
     /**
     *On window closing, 
     * Prompt the user to make sure they want to close the window.
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int confirmed = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to exit?", "Exit Program",
                JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param evt the event of what was pressed 
     * On help button pressed, show a help window of what to do and add. 
     */
    private void btn_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_helpActionPerformed
        JOptionPane.showConfirmDialog(null, "Please fill each text field:\n"
                + "Box Width: Please enter a width from 0cm - 999cm \n"
                + "Box Length: Please enter a length from 0cm - 999cm \n"
                + "Box Height: Please enter a height from 0cm - 999cm\n"
                + "Cardboard Grade: 1-5\n"
                + "Quantity: Please enter a quantity integer greater that 0\n"
                + "When all fields are full press add\n"
                + "Once all boxs are added press complete",
                "Box order help!", JOptionPane.CLOSED_OPTION);
    }//GEN-LAST:event_btn_helpActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
    }//GEN-LAST:event_formKeyReleased
     /**
     * @param evt the event of what was pressed 
     *Resets the error code on focus of the error text box.
     */
    private void txt_boxWidthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_boxWidthFocusGained
        resetError(evt);
    }//GEN-LAST:event_txt_boxWidthFocusGained
    
    /**
     * @param evt the event of what was pressed 
     * deletes a box based on the row that was selected. 
     */
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        //deletes the selected row in the order display table
        int row = tbl_boxOrders.getSelectedRow();
        if(row!= -1){
            orderManager.removeBox(row);
        DefaultTableModel model = (DefaultTableModel) tbl_boxOrders.getModel();
        model.removeRow(row);
        updateValues();
        }

    }//GEN-LAST:event_btn_deleteActionPerformed
/**
     * @param evt the event of what was pressed 
     * resets colour error on text field focus gained 
     */
    private void txt_boxLengthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_boxLengthFocusGained
        resetError(evt);
    }//GEN-LAST:event_txt_boxLengthFocusGained
/**
     * @param evt the event of what was pressed 
     * resets colour error on text field focus gained 
     */
    private void txt_boxHeightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_boxHeightFocusGained
       resetError(evt);
    }//GEN-LAST:event_txt_boxHeightFocusGained
/**
     * @param evt the event of what was pressed 
     * resets colour error on text field focus gained 
     */
    private void txt_quantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_quantityFocusGained
        resetError(evt);
    }//GEN-LAST:event_txt_quantityFocusGained
/**
     * @param evt the event of what was pressed 
     * On clicking complete order, a prompt with order totals appears. 
     */
    private void jbtn_completeOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_completeOrderMouseClicked
        DecimalFormat df = new DecimalFormat("0.00");
        String outputText = "Total order\n"
                + "Number of Boxes ordered "+ orderManager.getNumBoxes()+
                "\nTotal Cost of boxes £"+ df.format(orderManager.getAllCosts());
        JOptionPane.showConfirmDialog(null, outputText, "Final Order", JOptionPane.CLOSED_OPTION);
    }//GEN-LAST:event_jbtn_completeOrderMouseClicked

    /**
     * Clears the data inputted by user.
     */
    private void clearValues() {
        txt_boxHeight.setText("");
        txt_boxWidth.setText("");
        txt_boxLength.setText("");
        txt_quantity.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        rbtn_no1.setSelected(true);
        rbtn_no2.setSelected(true);
        rbtn_no3.setSelected(true);
        rbtn_0.setSelected(true);
        cmb_cardboardGrade.setSelectedIndex(0);
        txt_boxLength.setBackground(Color.white);
        txt_boxWidth.setBackground(Color.white);
        txt_boxHeight.setBackground(Color.white);
        txt_quantity.setBackground(Color.white);

    }


/**
     *Updates the data fields based by requesting the new values from 
     * Order manager.
     */
    private void updateValues() {
        noBoxes.setText("Num boxes: " + orderManager.getNumBoxes());
        DecimalFormat df = new DecimalFormat("0.00");
        totCost.setText("TotalCost: £" + df.format(orderManager.getAllCosts()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoxUI2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoxUI2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoxUI2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoxUI2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoxUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_help;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cmb_cardboardGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtn_add;
    private javax.swing.JButton jbtn_completeOrder;
    private javax.swing.JLabel noBoxes;
    private javax.swing.JRadioButton rbtn_0;
    private javax.swing.JRadioButton rbtn_1;
    private javax.swing.JRadioButton rbtn_2;
    private javax.swing.JRadioButton rbtn_no1;
    private javax.swing.JRadioButton rbtn_no2;
    private javax.swing.JRadioButton rbtn_no3;
    private javax.swing.JRadioButton rbtn_yes1;
    private javax.swing.JRadioButton rbtn_yes2;
    private javax.swing.JRadioButton rbtn_yes3;
    private javax.swing.JTable tbl_boxOrders;
    private javax.swing.JLabel totCost;
    private javax.swing.JTextField txt_boxHeight;
    private javax.swing.JTextField txt_boxLength;
    private javax.swing.JTextField txt_boxWidth;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables

    
/**
     *@param outputCode the code relating to which type of output it is. 
     * Selects which output is required based on the outputCode. 
     * 
     */
    private void outputPrompt(int outputCode) {
        if (outputCode < 0) {
            if (outputCode == -1) {
                notSupplied();
            } else {
                parameterError();
            }
        } else if (outputCode > 0) {
            JOptionPane.showConfirmDialog(null, "New Box " + outputCode +
                    " added to order", "Successfully Added Box", 
                    JOptionPane.CLOSED_OPTION);
        }
    }

    /**
     *Outputs error when the inputs are invalid. 
     */
    private void parameterError() {
        JOptionPane.showConfirmDialog(null, "New Boxes Failed To Add box\n"
                + "Check Inputs are valid", "ERROR ADDING BOX",
                JOptionPane.CLOSED_OPTION);
    }
/**
     *The selected type is valid but cannot be supplied by flex box
     */
    private void notSupplied() {
        //check if just a parameter error
        JOptionPane.showConfirmDialog(null, "Sorry\n"
                + "Flexbox does not supply this box", "ERROR ADDING BOX",
                JOptionPane.CLOSED_OPTION);
    }

    /**
     * @param evt the event of what was pressed 
     * resets specific colour error on text field focus gained 
     */
   private void resetError(java.awt.event.FocusEvent evt){
       evt.getComponent().setBackground(Color.white);
   }
}
