/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Order;

import static java.lang.Integer.parseInt;

/**
 *
 * @author felixmayo
 */
public class BoxUI2 extends javax.swing.JFrame {

    /**
     * Creates new form BoxUI2
     */
    public BoxUI2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jbtn_completeOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_boxSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cardboardGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtn_0 = new javax.swing.JRadioButton();
        rbtn_1 = new javax.swing.JRadioButton();
        rbtn_2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbtn_yes1 = new javax.swing.JRadioButton();
        rbtn_no1 = new javax.swing.JRadioButton();
        rbtn_yes2 = new javax.swing.JRadioButton();
        rbtn_no2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        jbtn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_completeOrder.setText("Complete Order");
        jbtn_completeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_completeOrderActionPerformed(evt);
            }
        });

        jLabel1.setText("Box Order Form");

        jLabel2.setText("Box size:");

        txt_boxSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_boxSizeActionPerformed(evt);
            }
        });

        jLabel3.setText("Cardboard grade:");

        jLabel4.setText("Colour print:");

        buttonGroup1.add(rbtn_0);
        rbtn_0.setText("0");
        rbtn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_0ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_1);
        rbtn_1.setText("1");
        rbtn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_2);
        rbtn_2.setText("2");

        jLabel5.setText("Renforced Bottom:");

        jLabel6.setText("Renforced Corners:");

        buttonGroup2.add(rbtn_yes1);
        rbtn_yes1.setText("Yes");
        rbtn_yes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_yes1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtn_no1);
        rbtn_no1.setText("No");
        rbtn_no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_no1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbtn_yes2);
        rbtn_yes2.setText("Yes");

        buttonGroup3.add(rbtn_no2);
        rbtn_no2.setText("No");

        jLabel7.setText("Quantity:");

        jbtn_add.setText("Add");
        jbtn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_addActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_cardboardGrade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rbtn_0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtn_1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtn_2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rbtn_yes1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtn_no1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rbtn_yes2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtn_no2))
                                    .addComponent(txt_boxSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_clear)
                        .addGap(101, 101, 101)
                        .addComponent(jbtn_add)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn_completeOrder)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(311, 311, 311))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_boxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cardboardGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtn_0)
                    .addComponent(rbtn_1)
                    .addComponent(rbtn_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtn_yes1)
                    .addComponent(rbtn_no1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtn_yes2)
                    .addComponent(rbtn_no2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_add)
                    .addComponent(btn_clear))
                .addGap(18, 18, 18)
                .addComponent(jbtn_completeOrder)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_0ActionPerformed

    private void rbtn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_1ActionPerformed

    private void rbtn_yes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_yes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_yes1ActionPerformed

    private void rbtn_no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_no1ActionPerformed

    private void jbtn_completeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_completeOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_completeOrderActionPerformed

    private void jbtn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_addActionPerformed
        // TODO add your handling code here:
        String boxSize = txt_boxSize.getText();
        String cardboardGrade = txt_cardboardGrade.getText();
        String quantity = txt_quantity.getText();
        int colourPrint = 3;
        boolean reBottom;
        boolean reCorners;
        
        
        //colour print
        if (rbtn_0.isSelected() == true) {
            colourPrint = 0;
        }
        if (rbtn_1.isSelected() == true) {
            colourPrint = 1;
        }
        if (rbtn_2.isSelected() == true) {
            colourPrint = 2;
        }
        //reinforced bottom
        if (rbtn_yes1.isSelected() == true) {
            reBottom = true;
        }
        if (rbtn_yes2.isSelected() == true) {
            reCorners = true;
        }
        
        if (colourPrint == 3 && Integer.parseInt(boxSize) > 0 && Integer.parseInt(quantity) > 0)  {
            // add the box as an object
            System.out.println("test");
        }
        else {
        clearValues();
        }
        
    }//GEN-LAST:event_jbtn_addActionPerformed

    private void txt_boxSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_boxSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_boxSizeActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clearValues();
    }//GEN-LAST:event_btn_clearActionPerformed

    
    private void clearValues(){
        txt_boxSize.setText("");
        txt_cardboardGrade.setText("");
        txt_quantity.setText("");
        rbtn_0.setSelected(false);
        rbtn_1.setSelected(false);
        rbtn_2.setSelected(false);
        rbtn_yes1.setSelected(false);
        rbtn_no1.setSelected(false);
        rbtn_yes2.setSelected(false);
        rbtn_no2.setSelected(false);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoxUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoxUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoxUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoxUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoxUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtn_add;
    private javax.swing.JButton jbtn_completeOrder;
    private javax.swing.JRadioButton rbtn_0;
    private javax.swing.JRadioButton rbtn_1;
    private javax.swing.JRadioButton rbtn_2;
    private javax.swing.JRadioButton rbtn_no1;
    private javax.swing.JRadioButton rbtn_no2;
    private javax.swing.JRadioButton rbtn_yes1;
    private javax.swing.JRadioButton rbtn_yes2;
    private javax.swing.JTextField txt_boxSize;
    private javax.swing.JTextField txt_cardboardGrade;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
